/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import domen.StavkaPorudzbine;
import domen.Zaposleni;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaKlijent;
import kontroler.KontrolerDobrodosli;
import transfer.TObjekat;
import view.konobar.NapraviPorudzbinu;
import view.konobar.NenaplacenePorudzbine;
import view.konobar.ProfilZaposlenog;
import view.konobar.SopstvenePorudzbine;
import view.model.ModelTableSanker;

/**
 *
 * @author Nevena
 */
public class Dobrodosli extends javax.swing.JFrame {
    Zaposleni zaposleni;
    KontrolerDobrodosli kontrolerD;
    /**
     * Creates new form Dobrodosli
     */
    public Dobrodosli(Zaposleni zaposleni) {
        this.zaposleni = zaposleni;
        initComponents();
        kontrolerD = new KontrolerDobrodosli();
        setTitle("Dobrodosli");
        jMenu1.setText(zaposleni.getIme());
        if (!zaposleni.getIme().equals("")) setBounds(0, 0, 400, 300);
        panelKonobar.setVisible(false);
        panelSanker.setVisible(false);
    }

    private Dobrodosli() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKonobar = new javax.swing.JPanel();
        buttonKreirajPorudzbinu = new javax.swing.JButton();
        buttonNenaplacene = new javax.swing.JButton();
        buttonSopstvene = new javax.swing.JButton();
        buttonProfil = new javax.swing.JButton();
        panelSanker = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        meniKonobar = new javax.swing.JMenuItem();
        meniSanker = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        meniOdjaviSe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonKreirajPorudzbinu.setText("Kreiraj porudzbinu");
        buttonKreirajPorudzbinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKreirajPorudzbinuActionPerformed(evt);
            }
        });

        buttonNenaplacene.setText("Nenaplaćene porudžbine");
        buttonNenaplacene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNenaplaceneActionPerformed(evt);
            }
        });

        buttonSopstvene.setText("Pregled sopstvenih porudžbina");
        buttonSopstvene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSopstveneActionPerformed(evt);
            }
        });

        buttonProfil.setText("Profil zaposlenog");
        buttonProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKonobarLayout = new javax.swing.GroupLayout(panelKonobar);
        panelKonobar.setLayout(panelKonobarLayout);
        panelKonobarLayout.setHorizontalGroup(
            panelKonobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKonobarLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(panelKonobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonKreirajPorudzbinu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNenaplacene, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSopstvene, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKonobarLayout.setVerticalGroup(
            panelKonobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKonobarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(buttonKreirajPorudzbinu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonNenaplacene, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSopstvene, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("Napravljena");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSankerLayout = new javax.swing.GroupLayout(panelSanker);
        panelSanker.setLayout(panelSankerLayout);
        panelSankerLayout.setHorizontalGroup(
            panelSankerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSankerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSankerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelSankerLayout.setVerticalGroup(
            panelSankerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSankerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(193, 193, 193))
        );

        jMenu1.setText("File");

        meniKonobar.setText("Konobar");
        meniKonobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniKonobarActionPerformed(evt);
            }
        });
        jMenu1.add(meniKonobar);

        meniSanker.setText("Šanker");
        meniSanker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniSankerActionPerformed(evt);
            }
        });
        jMenu1.add(meniSanker);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Odjava");

        meniOdjaviSe.setText("Odjavi se");
        meniOdjaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniOdjaviSeActionPerformed(evt);
            }
        });
        jMenu2.add(meniOdjaviSe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelKonobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSanker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelKonobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelSanker, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meniOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniOdjaviSeActionPerformed
        setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_meniOdjaviSeActionPerformed

    private void meniKonobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniKonobarActionPerformed
        panelSanker.setVisible(false);
        panelKonobar.setBounds(0, 0, 400, 280);
        panelKonobar.setVisible(true);
    }//GEN-LAST:event_meniKonobarActionPerformed

    private void meniSankerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniSankerActionPerformed
        panelKonobar.setVisible(false);
        panelSanker.setBounds(0, 0, 400, 280);
        kontrolerD.popuniTabelu(jTable1);
        panelSanker.setVisible(true);
    }//GEN-LAST:event_meniSankerActionPerformed

    private void buttonKreirajPorudzbinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKreirajPorudzbinuActionPerformed
        NapraviPorudzbinu np = new NapraviPorudzbinu(zaposleni);
        np.setVisible(true);
    }//GEN-LAST:event_buttonKreirajPorudzbinuActionPerformed

    private void buttonNenaplaceneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNenaplaceneActionPerformed
        NenaplacenePorudzbine nenaplacene = new NenaplacenePorudzbine();
        nenaplacene.setVisible(true);
    }//GEN-LAST:event_buttonNenaplaceneActionPerformed

    private void buttonSopstveneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSopstveneActionPerformed
        SopstvenePorudzbine sp = new SopstvenePorudzbine(zaposleni);
        sp.setVisible(true);
    }//GEN-LAST:event_buttonSopstveneActionPerformed

    private void buttonProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProfilActionPerformed
        ProfilZaposlenog pz = new ProfilZaposlenog(zaposleni);
        pz.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonProfilActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        kontrolerD.napravljenaStavka(jTable1, this);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dobrodosli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dobrodosli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dobrodosli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dobrodosli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dobrodosli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKreirajPorudzbinu;
    private javax.swing.JButton buttonNenaplacene;
    private javax.swing.JButton buttonProfil;
    private javax.swing.JButton buttonSopstvene;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem meniKonobar;
    private javax.swing.JMenuItem meniOdjaviSe;
    private javax.swing.JMenuItem meniSanker;
    private javax.swing.JPanel panelKonobar;
    private javax.swing.JPanel panelSanker;
    // End of variables declaration//GEN-END:variables

    
    
    public void postaviZaposlenog(Zaposleni izmenjenZaposleni) {
        zaposleni = izmenjenZaposleni;
    }
    
    public void konobar(){
        panelKonobar.setVisible(true);
    }
}
