/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import view.adminKreiraj.KreirajArtikal;
import view.adminKreiraj.KreirajDistributera;
import view.adminKreiraj.KreirajKategoriju;
import view.adminKreiraj.KreirajZaposlenog;
import view.adminPregled.PregledArtikala;
import view.adminPregled.PregledDistributera;
import view.adminPregled.PregledKategorija;
import view.adminPregled.PregledPorudzbina;
import view.adminPregled.PregledZaposlenih;

/**
 *
 * @author Nevena
 */
public class Admin extends javax.swing.JFrame {
    
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setTitle("Administratorska stranica");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        meniUlaz = new javax.swing.JMenu();
        meniUlazArtikala = new javax.swing.JMenuItem();
        meniKreiranje = new javax.swing.JMenu();
        meniKrairanjeArtikala = new javax.swing.JMenuItem();
        meniKreiranjeDistributera = new javax.swing.JMenuItem();
        meniKreiranjePorudzbina = new javax.swing.JMenuItem();
        meniKreiranjeZaposlenih = new javax.swing.JMenuItem();
        meniPregled = new javax.swing.JMenu();
        meniPregledArtikala = new javax.swing.JMenuItem();
        meniPregledDistributera = new javax.swing.JMenuItem();
        meniPregledKategorija = new javax.swing.JMenuItem();
        meniPregledPorudzbina = new javax.swing.JMenuItem();
        meniPregledZaposlenih = new javax.swing.JMenuItem();
        meniOdjava = new javax.swing.JMenu();
        meniOdjaviSe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Administrator");
        jMenuBar1.add(jMenu1);

        meniUlaz.setText("Ulaz");

        meniUlazArtikala.setText("Ulaz artikala");
        meniUlazArtikala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniUlazArtikalaActionPerformed(evt);
            }
        });
        meniUlaz.add(meniUlazArtikala);

        jMenuBar1.add(meniUlaz);

        meniKreiranje.setText("Kreiranje");

        meniKrairanjeArtikala.setText("Kreiranje artikala");
        meniKrairanjeArtikala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniKrairanjeArtikalaActionPerformed(evt);
            }
        });
        meniKreiranje.add(meniKrairanjeArtikala);

        meniKreiranjeDistributera.setText("Kreiranje distributera");
        meniKreiranjeDistributera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniKreiranjeDistributeraActionPerformed(evt);
            }
        });
        meniKreiranje.add(meniKreiranjeDistributera);

        meniKreiranjePorudzbina.setText("Kreiranje kategorija");
        meniKreiranjePorudzbina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniKreiranjePorudzbinaActionPerformed(evt);
            }
        });
        meniKreiranje.add(meniKreiranjePorudzbina);

        meniKreiranjeZaposlenih.setText("Kreiranje zaposlenih");
        meniKreiranjeZaposlenih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniKreiranjeZaposlenihActionPerformed(evt);
            }
        });
        meniKreiranje.add(meniKreiranjeZaposlenih);

        jMenuBar1.add(meniKreiranje);

        meniPregled.setText("Pregled");

        meniPregledArtikala.setText("Pregled artikala");
        meniPregledArtikala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniPregledArtikalaActionPerformed(evt);
            }
        });
        meniPregled.add(meniPregledArtikala);

        meniPregledDistributera.setText("Pregled distributera");
        meniPregledDistributera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniPregledDistributeraActionPerformed(evt);
            }
        });
        meniPregled.add(meniPregledDistributera);

        meniPregledKategorija.setText("Pregled kategorija");
        meniPregledKategorija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniPregledKategorijaActionPerformed(evt);
            }
        });
        meniPregled.add(meniPregledKategorija);

        meniPregledPorudzbina.setText("Pregled porudžbina");
        meniPregledPorudzbina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniPregledPorudzbinaActionPerformed(evt);
            }
        });
        meniPregled.add(meniPregledPorudzbina);

        meniPregledZaposlenih.setText("Pregled zaposlenih");
        meniPregledZaposlenih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniPregledZaposlenihActionPerformed(evt);
            }
        });
        meniPregled.add(meniPregledZaposlenih);

        jMenuBar1.add(meniPregled);

        meniOdjava.setText("Odjava");

        meniOdjaviSe.setText("Odjavi se");
        meniOdjaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniOdjaviSeActionPerformed(evt);
            }
        });
        meniOdjava.add(meniOdjaviSe);

        jMenuBar1.add(meniOdjava);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meniOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniOdjaviSeActionPerformed
        setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_meniOdjaviSeActionPerformed

    private void meniKrairanjeArtikalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniKrairanjeArtikalaActionPerformed
        KreirajArtikal artikal = new KreirajArtikal();
        artikal.setVisible(true);
    }//GEN-LAST:event_meniKrairanjeArtikalaActionPerformed

    private void meniKreiranjeDistributeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniKreiranjeDistributeraActionPerformed
        KreirajDistributera distributer = new KreirajDistributera();
        distributer.setVisible(true);
    }//GEN-LAST:event_meniKreiranjeDistributeraActionPerformed

    private void meniKreiranjePorudzbinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniKreiranjePorudzbinaActionPerformed
        KreirajKategoriju kategorija = new KreirajKategoriju();
        kategorija.setVisible(true);
    }//GEN-LAST:event_meniKreiranjePorudzbinaActionPerformed

    private void meniKreiranjeZaposlenihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniKreiranjeZaposlenihActionPerformed
        KreirajZaposlenog zaposleni = new KreirajZaposlenog();
        zaposleni.setVisible(true);
    }//GEN-LAST:event_meniKreiranjeZaposlenihActionPerformed

    private void meniUlazArtikalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniUlazArtikalaActionPerformed
        UlazArtikala ulaz = new UlazArtikala();
        ulaz.setVisible(true);
    }//GEN-LAST:event_meniUlazArtikalaActionPerformed

    private void meniPregledArtikalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniPregledArtikalaActionPerformed
        PregledArtikala artikli = new PregledArtikala();
        artikli.setVisible(true);
    }//GEN-LAST:event_meniPregledArtikalaActionPerformed

    private void meniPregledDistributeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniPregledDistributeraActionPerformed
        PregledDistributera distributeri = new PregledDistributera();
        distributeri.setVisible(true);
    }//GEN-LAST:event_meniPregledDistributeraActionPerformed

    private void meniPregledKategorijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniPregledKategorijaActionPerformed
        PregledKategorija kategorije = new PregledKategorija();
        kategorije.setVisible(true);
    }//GEN-LAST:event_meniPregledKategorijaActionPerformed

    private void meniPregledZaposlenihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniPregledZaposlenihActionPerformed
        PregledZaposlenih zaposleni = new PregledZaposlenih();
        zaposleni.setVisible(true);
    }//GEN-LAST:event_meniPregledZaposlenihActionPerformed

    private void meniPregledPorudzbinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniPregledPorudzbinaActionPerformed
        PregledPorudzbina porudzbine = new PregledPorudzbina();
        porudzbine.setVisible(true);
    }//GEN-LAST:event_meniPregledPorudzbinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem meniKrairanjeArtikala;
    private javax.swing.JMenu meniKreiranje;
    private javax.swing.JMenuItem meniKreiranjeDistributera;
    private javax.swing.JMenuItem meniKreiranjePorudzbina;
    private javax.swing.JMenuItem meniKreiranjeZaposlenih;
    private javax.swing.JMenu meniOdjava;
    private javax.swing.JMenuItem meniOdjaviSe;
    private javax.swing.JMenu meniPregled;
    private javax.swing.JMenuItem meniPregledArtikala;
    private javax.swing.JMenuItem meniPregledDistributera;
    private javax.swing.JMenuItem meniPregledKategorija;
    private javax.swing.JMenuItem meniPregledPorudzbina;
    private javax.swing.JMenuItem meniPregledZaposlenih;
    private javax.swing.JMenu meniUlaz;
    private javax.swing.JMenuItem meniUlazArtikala;
    // End of variables declaration//GEN-END:variables
}
