/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.adminPregled;

import domen.Artikal;
import domen.Distributer;
import domen.KategorijaArtikla;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaKlijent;
import transfer.TObjekat;
import view.model.ModelTableArtikli;
import view.model.ModelTableUlazArtikala;

/**
 *
 * @author Nevena
 */
public class PregledArtikala extends javax.swing.JFrame {

    /**
     * Creates new form PregledArtikala
     */
    public PregledArtikala() {
        initComponents();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        popuniTabelu();
        popuniCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        comboKategorija = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        buttonZatvori = new javax.swing.JButton();
        buttonObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pregled artikala");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        comboKategorija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboKategorija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKategorijaActionPerformed(evt);
            }
        });

        jLabel2.setText("Kategorija:");

        buttonZatvori.setText("Zatvori");
        buttonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZatvoriActionPerformed(evt);
            }
        });

        buttonObrisi.setText("Obriši artikal");
        buttonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonObrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonZatvori))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonZatvori)
                    .addComponent(buttonObrisi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZatvoriActionPerformed
        setVisible(false);
    }//GEN-LAST:event_buttonZatvoriActionPerformed

    private void comboKategorijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKategorijaActionPerformed
        try {
            KategorijaArtikla kategorija = (KategorijaArtikla) comboKategorija.getSelectedItem();
            TObjekat posalji = new TObjekat(null, "listaArtikala");
            KomunikacijaKlijent.vratiObjekat().posalji(posalji);
            TObjekat odgovor = KomunikacijaKlijent.vratiObjekat().procitaj();
            List<Artikal> artikli = (List<Artikal>) odgovor.getObjekat();
            List<Artikal> pronadjeniArtikli = new ArrayList<>();

            for (int i = 0; i < artikli.size(); i++) {
                if (artikli.get(i).getKategorija().equals(kategorija)) {
                    pronadjeniArtikli.add(artikli.get(i));
                }
            }

            ModelTableArtikli mta = new ModelTableArtikli(pronadjeniArtikli);
            jTable1.setModel(mta);

        } catch (IOException ex) {
            Logger.getLogger(PregledArtikala.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PregledArtikala.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboKategorijaActionPerformed

    private void buttonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonObrisiActionPerformed
        int brojRedova = jTable1.getModel().getRowCount();
        int rb = jTable1.getSelectedRow();
        if (rb == -1) {
            JOptionPane.showMessageDialog(this, "Selektuj red!");
        } else {
            try {
                ModelTableArtikli mta = (ModelTableArtikli) jTable1.getModel();
                Artikal artikal = mta.vratiObjekat(rb);
                
                TObjekat posalji = new TObjekat(artikal, "obrisiArtikal");
                KomunikacijaKlijent.vratiObjekat().posalji(posalji);
                TObjekat odgovor = KomunikacijaKlijent.vratiObjekat().procitaj();
                
                mta.obrisiRed(rb);
            } catch (IOException ex) {
                Logger.getLogger(PregledArtikala.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PregledArtikala.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PregledArtikala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PregledArtikala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PregledArtikala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PregledArtikala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PregledArtikala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonObrisi;
    private javax.swing.JButton buttonZatvori;
    private javax.swing.JComboBox comboKategorija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void popuniTabelu() {
        try {
            TObjekat posalji = new TObjekat(null, "listaArtikala");
            KomunikacijaKlijent.vratiObjekat().posalji(posalji);
            TObjekat odgovor = KomunikacijaKlijent.vratiObjekat().procitaj();

            List<Artikal> artikli = (List<Artikal>) odgovor.getObjekat();
            ModelTableArtikli mta = new ModelTableArtikli(artikli);
            jTable1.setModel(mta);
        } catch (IOException ex) {
            Logger.getLogger(PregledArtikala.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PregledArtikala.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void popuniCombo() {
        try {
            TObjekat posalji = new TObjekat(null, "listaKategorija");
            KomunikacijaKlijent.vratiObjekat().posalji(posalji);
            TObjekat odgovor = KomunikacijaKlijent.vratiObjekat().procitaj();
            List<KategorijaArtikla> kategorije = (List<KategorijaArtikla>) odgovor.getObjekat();

            comboKategorija.setModel(new DefaultComboBoxModel(kategorije.toArray()));
        } catch (IOException ex) {
            Logger.getLogger(PregledArtikala.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PregledArtikala.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
