/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.konobar;

import domen.Artikal;
import domen.NovaPorudzbina;
import domen.Porudzbina;
import domen.Razduzenje;
import domen.StavkaPorudzbine;
import domen.Ulaz;
import domen.Zaposleni;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import komunikacija.KomunikacijaKlijent;
import kontroler.KontrolerNapraviPorudzbinu;
import transfer.TObjekat;
import view.model.ModelTableNapraviPorudzbinu;
import view.model.ModelTableUlazArtikala;

/**
 *
 * @author Nevena
 */
public class NapraviPorudzbinu extends javax.swing.JFrame {
    Zaposleni zaposleni;
    Porudzbina izmeniPorudzbinu;
    List<StavkaPorudzbine> listaStavki;
    KontrolerNapraviPorudzbinu kontrolerNP;
    /**
     * Creates new form NapraviPorudzbinu
     */
    public NapraviPorudzbinu(Zaposleni zaposleni) {
        kontrolerNP = new KontrolerNapraviPorudzbinu();
        this.zaposleni = zaposleni;
        initComponents();
        kontrolerNP.popuniTabelu(jTable1, zaposleni);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        textBroj.setEditable(false);
        buttonIzmeni.setVisible(false);
        kontrolerNP.vratiID(textBroj, zaposleni);
    }

    public NapraviPorudzbinu(Porudzbina izmeniPorudzbinu) {
        kontrolerNP = new KontrolerNapraviPorudzbinu();
        this.izmeniPorudzbinu = izmeniPorudzbinu;
        initComponents();
        kontrolerNP.popuniTabelu(jTable1, zaposleni);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        textBroj.setEditable(false);
        kontrolerNP.izmeniPorudzbinu(izmeniPorudzbinu, jTable1, zaposleni, textBroj, textDatum, checkBox1);
        buttonSacuvaj.setVisible(false);
    }
    

    private NapraviPorudzbinu() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textBroj = new javax.swing.JTextField();
        textDatum = new javax.swing.JTextField();
        checkBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonDodaj = new javax.swing.JButton();
        buttonUkloni = new javax.swing.JButton();
        buttonSacuvaj = new javax.swing.JButton();
        buttonOtkazi = new javax.swing.JButton();
        buttonIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Kreiranje porudžbine");

        jLabel2.setText("Broj porudžbine:");

        jLabel3.setText("Datum:");

        jLabel4.setText("Razduženo:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buttonDodaj.setText("Dodaj");
        buttonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDodajActionPerformed(evt);
            }
        });

        buttonUkloni.setText("Ukloni");
        buttonUkloni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUkloniActionPerformed(evt);
            }
        });

        buttonSacuvaj.setText("Sačuvaj porudžbinu");
        buttonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSacuvajActionPerformed(evt);
            }
        });

        buttonOtkazi.setText("Otkaži");
        buttonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOtkaziActionPerformed(evt);
            }
        });

        buttonIzmeni.setText("Izmeni porudžbinu");
        buttonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkBox1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(textDatum)
                            .addComponent(textBroj)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(buttonUkloni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 274, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonOtkazi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkBox1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonDodaj)
                        .addGap(18, 18, 18)
                        .addComponent(buttonUkloni))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSacuvaj)
                    .addComponent(buttonOtkazi)
                    .addComponent(buttonIzmeni))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDodajActionPerformed
        ModelTableNapraviPorudzbinu mtnp = (ModelTableNapraviPorudzbinu) jTable1.getModel();
        NovaPorudzbina np = new NovaPorudzbina();
        Artikal a = new Artikal();
        np.setArtikal(a);
        mtnp.dodajRed(np);
    }//GEN-LAST:event_buttonDodajActionPerformed

    private void buttonUkloniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUkloniActionPerformed
        int rb = jTable1.getSelectedRow();
        if (rb == -1) {
            JOptionPane.showMessageDialog(this, "Selektuj red!");
		} else {
            ModelTableNapraviPorudzbinu mtnp = (ModelTableNapraviPorudzbinu) jTable1.getModel();
            mtnp.obrisiRed(rb);
        }
    }//GEN-LAST:event_buttonUkloniActionPerformed

    private void buttonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOtkaziActionPerformed
        setVisible(false);
    }//GEN-LAST:event_buttonOtkaziActionPerformed

    private void buttonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSacuvajActionPerformed
        kontrolerNP.sacuvaj(jTable1, zaposleni, textBroj, textDatum, checkBox1);
    }//GEN-LAST:event_buttonSacuvajActionPerformed

    private void buttonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIzmeniActionPerformed
        kontrolerNP.izmeni(jTable1, zaposleni, textBroj, textDatum, checkBox1);
        
    }//GEN-LAST:event_buttonIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NapraviPorudzbinu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NapraviPorudzbinu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NapraviPorudzbinu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NapraviPorudzbinu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NapraviPorudzbinu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDodaj;
    private javax.swing.JButton buttonIzmeni;
    private javax.swing.JButton buttonOtkazi;
    private javax.swing.JButton buttonSacuvaj;
    private javax.swing.JButton buttonUkloni;
    private javax.swing.JCheckBox checkBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textBroj;
    private javax.swing.JTextField textDatum;
    // End of variables declaration//GEN-END:variables

    
    
    
    
    
    
    
}
