/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.adminPregled;

import domen.Distributer;
import domen.Porudzbina;
import domen.Zaposleni;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import komunikacija.KomunikacijaKlijent;
import transfer.TObjekat;
import view.model.ModelTablePorudzbine;

/**
 *
 * @author Nevena
 */
public class PregledPorudzbina extends javax.swing.JFrame {

    /**
     * Creates new form PregledPorudzbina
     */
    public PregledPorudzbina() {
        initComponents();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        popuniTabelu();
        popuniCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textOd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textDo = new javax.swing.JTextField();
        comboZaposleni = new javax.swing.JComboBox();
        buttonPronadji = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonZatvori = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pregled porudzbina");

        jLabel2.setText("Zaposleni:");

        jLabel3.setText("Datum od:");

        jLabel4.setText("Datum do:");

        comboZaposleni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboZaposleniActionPerformed(evt);
            }
        });

        buttonPronadji.setText("Pronađi");
        buttonPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPronadjiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buttonZatvori.setText("Zatvori");
        buttonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZatvoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboZaposleni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textOd))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(12, 12, 12)
                                .addComponent(textDo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonPronadji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonZatvori)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPronadji))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(buttonZatvori)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZatvoriActionPerformed
        setVisible(false);
    }//GEN-LAST:event_buttonZatvoriActionPerformed

    private void comboZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboZaposleniActionPerformed
        try {
            Zaposleni zaposleni = (Zaposleni)comboZaposleni.getSelectedItem();
            TObjekat posalji = new TObjekat(null, "listaPorudzbina");
            KomunikacijaKlijent.vratiObjekat().posalji(posalji);
            TObjekat odgovor = KomunikacijaKlijent.vratiObjekat().procitaj();
            List<Porudzbina> porudzbine = (List<Porudzbina>) odgovor.getObjekat();
            List<Porudzbina> pronadjenePorudzbine = new ArrayList<>();
            
            for (int i = 0; i<porudzbine.size(); i++){
                if (porudzbine.get(i).getZaposleni().getIme().equals(zaposleni.getIme()) &&
                        porudzbine.get(i).getZaposleni().getPrezime().equals(zaposleni.getPrezime()))
                    pronadjenePorudzbine.add(porudzbine.get(i));
            }
            
            ModelTablePorudzbine mtp = new ModelTablePorudzbine(pronadjenePorudzbine);
            jTable1.setModel(mtp);
        } catch (IOException ex) {
            Logger.getLogger(PregledPorudzbina.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PregledPorudzbina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboZaposleniActionPerformed

    private void buttonPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPronadjiActionPerformed
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumOdUtil = sdf.parse(textOd.getText());
            Date datumDoUtil = sdf.parse(textDo.getText());
            java.sql.Date datumOd = new java.sql.Date(datumOdUtil.getTime());
            java.sql.Date datumDo = new java.sql.Date(datumDoUtil.getTime());
            
            TObjekat posalji = new TObjekat(null, "listaPorudzbina");
            KomunikacijaKlijent.vratiObjekat().posalji(posalji);
            TObjekat odgovor = KomunikacijaKlijent.vratiObjekat().procitaj();
            List<Porudzbina> porudzbine = (List<Porudzbina>) odgovor.getObjekat();
            List<Porudzbina> pronadjenePorudzbine = new ArrayList<>();
            
            for (int i = 0; i<porudzbine.size(); i++){
                if (porudzbine.get(i).getDatumPorudzbine().after(datumOd) &&
                        porudzbine.get(i).getDatumPorudzbine().before(datumDo))
                    pronadjenePorudzbine.add(porudzbine.get(i));
            }
            
            ModelTablePorudzbine mtp = new ModelTablePorudzbine(pronadjenePorudzbine);
            jTable1.setModel(mtp);
        } catch (ParseException ex) {
            Logger.getLogger(PregledPorudzbina.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PregledPorudzbina.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PregledPorudzbina.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buttonPronadjiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PregledPorudzbina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PregledPorudzbina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PregledPorudzbina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PregledPorudzbina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PregledPorudzbina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPronadji;
    private javax.swing.JButton buttonZatvori;
    private javax.swing.JComboBox comboZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textDo;
    private javax.swing.JTextField textOd;
    // End of variables declaration//GEN-END:variables

    public void popuniTabelu() {
        try {
            TObjekat posalji = new TObjekat(null, "listaPorudzbina");
            KomunikacijaKlijent.vratiObjekat().posalji(posalji);
            TObjekat odgovor = KomunikacijaKlijent.vratiObjekat().procitaj();
            List<Porudzbina> porudzbine = (List<Porudzbina>) odgovor.getObjekat();

            ModelTablePorudzbine mtp = new ModelTablePorudzbine(porudzbine);
            jTable1.setModel(mtp);
        } catch (IOException ex) {
            Logger.getLogger(PregledPorudzbina.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PregledPorudzbina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void popuniCombo() {
        try {
            TObjekat posalji = new TObjekat(null, "listaZaposlenih");
            KomunikacijaKlijent.vratiObjekat().posalji(posalji);
            TObjekat odgovor = KomunikacijaKlijent.vratiObjekat().procitaj();
            List<Zaposleni> zaposleneOsobe = (List<Zaposleni>) odgovor.getObjekat();

            comboZaposleni.setModel(new DefaultComboBoxModel(zaposleneOsobe.toArray()));
        } catch (IOException ex) {
            Logger.getLogger(PregledPorudzbina.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PregledPorudzbina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
